pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "76625/java-app"
        DOCKER_CREDENTIALS_ID = "dockerhub-creds"
        KUBECONFIG_CREDENTIALS_ID = "kubeconfig-creds"
    }

    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/your-repo/your-java-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build(DOCKER_IMAGE)
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('', DOCKER_CREDENTIALS_ID) {
                        docker.image(DOCKER_IMAGE).push()
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                withCredentials([file(credentialsId: KUBECONFIG_CREDENTIALS_ID, variable: 'KUBECONFIG')]) {
                    sh '''
                        export KUBECONFIG=$KUBECONFIG
                        kubectl apply -f deployment.yaml
                        kubectl apply -f service.yaml
                    '''
                }
            }
        }
    }
}
